databases:
  - name: postgres
    ipAllowList: []
    databaseName: DepositApp_production
    user: DepositApp

services:
  - type: web
    name: rails 
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: DepositApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis 
    name: redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction