databases:
  - name: DepositApp
    databaseName: DepositApp
    user: DepositApp_user

services:
  - type: web
    name: DepositApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverse-rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false