default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: ridwan

development:
  <<: *default
  database: DepositApp_development
  
test:
  <<: *default
  database: DepositApp_test
# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
# 
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
# 
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>