default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: ridwan

development:
  <<: *default
  database: DepositApp_development

test:
  <<: *default
  database: DepositApp_test


production:
  <<: *default
  database: DepositApp_production
  username: DepositApp
  password: <%= ENV["MYAPP_DATABASE_PASSWORD"] %>
